version: '3'

services:
  php:
    image: php:7.4-fpm
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: loc-poisk # create this database on startup
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8082:80"
    environment:
      # MYSQL_ROOT_PASSWORD: mypassword #(Required) set the password for the root superuser account.
      PMA_HOST: mysql   # define the address/hostname of the mysql server eg mysql container name.
      # PMA_USER: root # this is the root user to login on startup
      # PMA_PASSWORD: mypassword # use the root password to login on startup.