version: '3'

services:
  php:
    image: php:7.4-fpm
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: loc-poisk
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8082:80"
    environment:
      PMA_HOST: mysql      