version: '3'

services:
  php:
    # image: php:7.4-fpm
    build: /php
    volumes:
      - './src:/var/www/html'
    depends_on: 
      - mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: loc-poisk
      
  crond:
    build: /crond  
    restart: unless-stopped
    volumes:
      - ./files:/var/files:ro  
    depends_on: 
      - mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: loc-poisk

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      
  mysql:
    # build: /mysql
    # container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    # command: ["apt-get", "install","-y","cron"]
    # command: ["cron","-f"]
    restart: unless-stopped
    volumes:
      # - ./files:/var/files:ro
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: loc-poisk
    ports:
      - '3306:3306'
